### PR TITLE
Detect the latest version of ASM API automatically.

### LINKED ISSUE #74: Unable to transform class related to record.
Consider the following use case:
```java
package com.example;
public record ExampleRecord(String name) {}
```
```java
package com.example.mixin;

import com.example.ExampleRecord;
import net.minecraft.client.main.Main;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(Main.class)
public class MixinMain {
    @Inject(method = "main", at = @At("HEAD"))
    private static void inject$main(String[] args, CallbackInfo ci) {
        try {
            ExampleRecord record = new ExampleRecord("");
        } catch (Throwable t) {}
    }
}
```

The above code will throw the following exception:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Record requires ASM8
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
Caused by: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:151)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:83)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:63)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:631)
	at java.base/java.lang.Class.forName(Class.java:543)
	at MC-BOOTSTRAP/fmlloader@1.17.1-37.0.61/net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
```

This is caused by `SuperCollectingVisitor` using ASM7 which does not support record:
https://github.com/cpw/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/TransformerClassWriter.java#L168-L170

### PR DESCRIPTION
**Pull request by ZekerZhayard**
Fix #74

### CODE REVIEW

**Comment by Mumfrey** [comment]
Can I just say, if you [copied this idea from Mixin](https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/main/java/org/spongepowered/asm/util/asm/ASM.java#L160), then you missed an important part of the puzzle. And if you didn't copy the idea and came up with it yourself then you still need to be aware of the pitfalls.

Yes Mixin does this, but it doesn't just blindly accept the value it finds, since the value returned is woven in to the compatibility level checks, and there are corresponding [shims](https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/main/java/org/spongepowered/asm/util/asm/ClassNodeAdapter.java) and various checks littered around the codebase to make sure that it respects the limitations of the ASM version in use. The reason it does this is that Mixin is still backward compatible back to **ASM 5** but compatible all the way up to current versions of ASM. _The functionality isn't there because it's onerous to **do a simple search and replace of the ASM API version** when updating, it's there because certain things just wouldn't be able to support the huge span of versions otherwise._

Why does this matter?

Because this PR seems to be copying the behaviour without understanding the purpose, and without realising why ASM has this contract in the first place. And even if you haven't copied the behaviour and have come up with the idea yourself, you're still missing the latter point. You've taken a simple oversight in bumping the constant to match the ASM library version, and decided that the constant itself must therefore be the problem.

This could be fixed trivially and reliably by updating the constants in the appropriate place, or if you insist that it's necessary then the relevant version sanity checks need to exist elsewhere like they do in Mixin. But just having this PR as-written is over-engineered to fix the "forgot to change a constant" problem, but under-engineered to solve the follow-on problems created by its inclusion.

Also your description claims to `Fix #74` but doesn't explain how it takes into account any changes required to ModLauncher to properly support records other than "it won't crash any more". Writing more than 2 words in a PR description shows you've actually thought about solving a problem and haven't just come up with some half-assed work-around which solves the immediate problem but causes 10 others.

**Comment by Mumfrey** [comment]
Corollary: centralising the API constant so it's less onerous to change it (or at least has a smaller commit footprint when doing so) isn't itself an intrinsically awful idea, since it could be generally argued that it's equivalent to doing a search-n-replace anyway, but detecting the version without any form of validation is unnecessarily lazy and introduces possible failure modes which are not accounted for in any way.

**Comment by ZekerZhayard** [comment]
>Because this PR seems to be copying the behaviour without understanding the purpose, and without realising why ASM has this contract in the first place. And even if you haven't copied the behaviour and have come up with the idea yourself, you're still missing the latter point. You've taken a simple oversight in bumping the constant to match the ASM library version, and decided that the constant itself must therefore be the problem.

I really can't fully understand the purpose of the ASM API version. However, I think modlauncher and mixin are different in sensitivity to it. Modlauncher does not need to transform classes like mixin, it only needs to parse a class into ClassNode, and modders completes the rest, so I think the "shims" you showed should be paid attention to by modders, not modlauncher. 

>This could be fixed trivially and reliably by updating the constants in the appropriate place, or if you insist that it's necessary then the relevant version sanity checks need to exist elsewhere like they do in Mixin. But just having this PR as-written is over-engineered to fix the "forgot to change a constant" problem, but under-engineered to solve the follow-on problems created by its inclusion.

If it is possible to only modify the ASM API version, I am willing to do so. From previous discussions, I think that forge team may not welcome the modification of only one or two lines of PR, so I decided to use some solutions that can be stable within the foreseeable range instead of just modifying the ASM API version, because it needs to be modified again after upgrading ASM. 

>Also your description claims to Fix #74 but doesn't explain how it takes into account any changes required to ModLauncher to properly support records other than "it won't crash any more" (or at the very least explaining that you've checked that there aren't any). Writing more than 2 words in a PR description shows you've actually thought about solving a problem and haven't just come up with some half-assed work-around which solves the immediate problem but causes 10 others.

I'm really not good at discussing with people. I have squeezed out the above words for a long time. This PR has only two words to explain because I think what I want to say has already been said in #74. 

>Corollary: centralising the API constant so it's less onerous to change it (or at least has a smaller commit footprint when doing so) isn't itself an intrinsically awful idea, since it could be generally argued that it's equivalent to doing a search-n-replace anyway, but detecting the version without any form of validation is unnecessarily lazy and introduces possible failure modes which are not accounted for in any way.

Yes, I also feel that my consideration is not rigorous enough, so what should I do to appear thoughtful?

**Comment by Mumfrey** [comment]
> I really can't fully understand the purpose of the ASM API version.

So what you're saying is that without understanding its relevance, you elected to make changes you don't understand?

> However, I think modlauncher and mixin are different in sensitivity to it. Modlauncher does not need to transform classes like mixin, it only needs to parse a class into ClassNode, and modders completes the rest. so I think the "shims" you showed should be paid attention to by modders, not modlauncher.

This still isn't an argument for making it dynamic, and I think you misunderstood the purpose of the shims. The functionality in Mixin is specifically there because Mixin supports many versions of ASM, ModLauncher does not need to support multiple versions of ASM, just the one it releases with. The entire problem here is as simple as the API constant was missed when the ASM version was bumped.

> If it is possible to only modify the ASM API version, I am willing to do so. From previous discussions, I think that forge team may not welcome the modification of only one or two lines of PR, so I decided to use some solutions that can be stable within the foreseeable range instead of just modifying the ASM API version, because it needs to be modified again after upgrading ASM.

This reads as "I decided to over-engineer my PR because the obvious solution wasn't complex enough".

> Yes, I also feel that my consideration is not rigorous enough, so what should I do to appear thoughtful?

Actually describe the reasoning for your changes and how they address the problem would be a start.

**Comment by OrionDevelopment** [comment]
To be honest we should just inject this data from gradle.....
Set the gradle ASM version in the buildscript -> Update the version automatically in some central value -> reference this from everywhere

**Comment by cpw** [comment]
> Corollary: centralising the API constant so it's less onerous to change it (or at least has a smaller commit footprint when doing so) isn't itself an intrinsically awful idea, since it could be generally argued that it's equivalent to doing a search-n-replace anyway, but detecting the version without any form of validation is unnecessarily lazy and introduces possible failure modes which are not accounted for in any way.

I had considered doing this, but given the lack of complete testing, I don't consider it valid. The version of ASM declared in each of the various transformer locations is the version it was tested with, where appropriate. Arbitrarily bumping the numbers, even in lock step like this, should only be done once we have a fully comprehensive test suite to validate against all versions of the JVM we expect to encounter.




> This still isn't an argument for making it dynamic, and I think you misunderstood the purpose of the shims. The functionality in Mixin is specifically there because Mixin supports many versions of ASM, ModLauncher does not need to support multiple versions of ASM, just the one it releases with. The entire problem here is as simple as the API constant was missed when the ASM version was bumped.

As said above - this constant is left at the lowest number that is _tested to work_. 



> To be honest we should just inject this data from gradle.....
> Set the gradle ASM version in the buildscript -> Update the version automatically in some central value -> reference this from everywhere

Not without full coverage in a test suite, I would not like to do that.

**Pull request closed without merging**
